name:                functional-data-structure-challenges
version:             0.1.0.0
github:              starcolon/functional-data-structure-challenges
license:             BSD3
author:              TaoPR
maintainer:          TaoPR
copyright:           2017 TaoPR

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A fun functional programming challenges 
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/starcolon/functional-data-structure-challenges#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- hspec-discover
- QuickCheck
- containers >= 0.5.7.1

library:
  source-dirs: src

executables:
  functional-data-structure-challenges-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functional-data-structure-challenges

tests:
  functional-data-structure-challenges-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functional-data-structure-challenges
